const map = new mapboxgl.Map({
  container: "map",
  style: "mapbox://styles/mapbox/streets-v11",
  center: [103.82364, 1.26396],
  zoom: 16,
});

map.on("load", () => {
  map.addSource("data", {
    type: "geojson",
    // JSON data load from iframe, generated by geojson.io
    data: window.geojsonData,
  });

  map.addLayer({
    id: "nodes-layer",
    type: "symbol",
    source: "data",
    layout: {
      "icon-image": "rocket-15",
      "icon-allow-overlap": true,
      "symbol-placement": "line",
      "symbol-spacing": 1, // default 250px
      "icon-image": "rocket-15",
      "icon-rotate": 45
    },
  });
});

const handleMapChange = () => {
  console.log("handleMapChange", map.getCenter(), map.getBounds());
};

map.on("zoomend", handleMapChange);
map.on("dragend", handleMapChange);
