const map = new mapboxgl.Map({
  container: "map",
  style: "mapbox://styles/mapbox/streets-v11",
  center: [103.824, 1.2649],
  zoom: 19,
});

map.on("load", () => {
  map.addSource("data", {
    type: "geojson",
    data: window.geojsonData, // JSON data load from iframe, generated by geojson.io
  });

  map.addLayer({
    id: "point-layer",
    type: "circle",
    source: "data",
    paint: {
      "circle-color": "red",
      "circle-opacity": 0.5,
      "circle-radius": 50,
    },
  });
});
